### ISSUE TITLE
Common alerts to share?

### ISSUE THREAD

**Issue by samber** [nats-io/prometheus-nats-exporter#226]
Hi there 👋

@sfarwassim just opened an issue on [samber/awesome-prometheus-alerts](https://github.com/samber/awesome-prometheus-alerts/issues/350) to request contributions.

Do you have nice Prometheus alerts to share, for NATS monitoring?

**Comment by Ruthercode** [comment]
Something like this?

```yaml
groups:
- name: NATSAlerts
  rules:
  - alert: HighConnectionCount
    expr: gnatsd_varz_connections > 100
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High number of NATS connections ({{ $value }})"
      description: "The number of NATS connections is greater than 100 for {{ $labels.instance }}"

  - alert: HighPendingBytes
    expr: gnatsd_connz_pending_bytes > 100000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High number of NATS pending bytes ({{ $value }})"
      description: "The number of NATS pending bytes is greater than 100000 for {{ $labels.instance }}"

  - alert: HighSubscriptionsCount
    expr: gnatsd_connz_subscriptions > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High number of NATS subscriptions ({{ $value }})"
      description: "The number of NATS subscriptions is greater than 50 for {{ $labels.instance }}"

  - alert: HighRoutesCount
    expr: gnatsd_routez_num_routes > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High number of NATS routes ({{ $value }})"
      description: "The number of NATS routes is greater than 10 for {{ $labels.instance }}"

```
