### ISSUE TITLE
Create official docker images

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/prometheus-nats-exporter#48]
https://github.com/docker-library/official-images/pull/4069

**Comment by camsjams** [comment]
Looking forward to it

**Comment by koliyo** [comment]
I just noticed that it is allowed to use git urls as build context for docker compose. This is what I currently use

```
  prometheus-nats-exporter:
    build:
      context: https://github.com/nats-io/prometheus-nats-exporter.git
      dockerfile: docker/linux/amd64/Dockerfile
```
