### ISSUE TITLE
ignoring server http://localhost:8222: invalid character 'p' after top-level value

### ISSUE THREAD

**Issue by wallyqs** [nats-io/prometheus-nats-exporter#88]
Getting this error when starting prometheus exporter image as follows:

```yaml
      - name: metrics
        image: synadia/prometheus-nats-exporter:0.4.0
        args:
        - -connz
        - -routez
        - -subz
        - -varz
        - -prefix=nats
        - -DV
        - http://localhost:8222/
```

**Comment by wallyqs** [comment]
Seems this goes away if including an extra slash to the route:

```yaml
      - name: metrics
        image: synadia/prometheus-nats-exporter:0.4.0
        args:
        - -connz
        - -routez
        - -subz
        - -varz
        - -prefix=nats
        - -DV
        - http://localhost:8222/
```

**Comment by wallyqs** [comment]
Also `invalid character 'p' after top-level value` probably means `page not found`

**Comment by manuel-koch** [comment]
I'm using it in my docker-compose setup like

```yaml
  nats-metrics:
    image: natsio/prometheus-nats-exporter:0.15.0
    command: [ "-D", "-channelz", "http://nats-server:8222" ]
```

and regardless of a trailing `/` for the URL, I always get `ignoring server http://nats-server:8222: invalid character 'p' after top-level value`.
It only vanishes when I don't use that `-channelz` switch.
Using other switches like `-varz`, `-connz`, `-jsz=all`, `-serverz` or `-subz` don't seem to trigger this debug message.
